config/routes.rb
Swimapp::Application.routes.draw do
  resources :not_workouts

  root 'static_pages#home'
  match '/shallow_end', to: 'static_pages#shallow_end', via: 'get'
  match '/deep_end', to: 'static_pages#deep_end', via: 'get'
  match '/help',	to: 'static_pages#help',	via: 'get'
  match '/about',	to: 'static_pages#about',	via: 'get'
  match '/contact',	to: 'static_pages#contact',	via: 'get'

  

  resources :workouts

  devise_for :users, :controllers => {:registrations => "registrations"}

end

app/models/goal.rb
class Goal
	#attr_accessor :goal

	def get_goal(user)
		return user.goal
	end
end

app/models/totaler.rb
class Totaler

	def get_total(user)
		total = 0
		user.workouts.each { |x| total += x.distance_as_miles}
		return total
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :workouts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/workout.rb
class Workout < ActiveRecord::Base

  belongs_to :user

  def distance_as_miles
    MilesConverter.new(units).convert(distance)
  end

end

class MilesConverter
  attr_reader :units
  def initialize(units = 'yards')
    @units = units
  end

  def convert(distance)
    distance * conversion(@units)
  end

  def conversion(unit)
    case unit
    when 'meters'
      return 0.000621371
    when 'yards'
      return 0.000568182
    else
      return 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < Devise::RegistrationsController

	def new
		@goal = current_user.goal
	end

	def show
	end

	def edit
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	before_filter :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :goal
		devise_parameter_sanitizer.for(:account_update) << :goal
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	@user = current_user
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = current_user.workouts.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create

#this is what I had before:
#w = Workout.new(distance: params[:distance], units: params[:units])
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:distance, :units, :references)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/not_workouts_helper.rb
module NotWorkoutsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Swim App by Joel Mikkelsen
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div>
    <div>
      <%= link_to "Swim App", root_path, id:"logo" %>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Sign in", user_session_path %></li>  
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_menu.html.erb
<%= javascript_include_tag "application", "borderMenu", "classie", :modernizr, "data-turbolinks-track" => true %>
<%#= javascript_include_tag "borderMenu", "classie", "modernizr", "data-turbolinks-track" => true %>

<%= stylesheet_link_tag "application", "normalize", "style5", media: "all",
                                           "data-turbolinks-track" => true %>
<nav id="bt-menu" class="bt-menu">
<a href="#" class="bt-menu-trigger"><span>Menu</span></a>
	<ul>
		<li><%= link_to "Home", root_path %></li>
        <!--li><%#= link_to "Help", help_path %></li-->
        <li><%= link_to "Shallow end", shallow_end_path %></li>
        <li><%= link_to "Deep end", deep_end_path %></li>
          
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path %></li>
          <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign in", user_session_path %></li>  
        <% end %>

	
	</ul>
	<!--ul>
		<li><%= link_to "About",  about_path %></li>
    	<li><%= link_to "Contact", contact_path %></li>
    	<li><a href="http://www.joelmikkelsen.com" target="_blank">Blog</a></li>
		<li><a href="https://github.com/joeldmikk">Github</a></li>
	</ul-->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Swim Challenge | <%= yield(:title) %></title>
    
    <%= javascript_include_tag "application", "borderMenu", "classie", :modernizr, "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "application", "normalize", "style5", media: "all",
                                           "data-turbolinks-track" => true %>
   	<%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <!--script src="vendor/modernizr.js"></script-->

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/menu' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About SwimApp</h1>
<p>I had three goals for this year: make a rails app, swim 100 miles, and kill two birds with one stone. This project should help with all three.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact me at my email@emailaddress.com
</p>

app/views/static_pages/deep_end.html.erb
<% provide(:title, 'Deep End') %>
<div class="container">
  <%= image_tag("swim_icon_white.png", size: "50") %>

  <h1>The Deep End</h1>

  <h2>
    Experienced Swimmers Start Here
  </h2>

  <div class="text_bg">
    <h3>
    What should I do for a workout?
    </h3>
    <p>I like to go for long, uninterrupted swims. But the most effective way to train is to do high intensity interval sets, in which you swim hard for short distances and rest in between.</p>
    <p><%= link_to "Swim Plan", 'http://www.swimplan.com', class: 'text_link' %> is a great resource that gives you customized daily workouts based on your ability and desired workout length.</p>
    <p>If you're serious about improving as a swimmer, you should dedicate some time each week to drills designed to refine your technique. You can easily find drills on the internet, and the <%= link_to "US Masters Swimming", 'http://www.usms.org', class: 'text_link' %> website has some <%= link_to "great drills", 'http://www.usms.org/articles/articlesearch.php?CategoryID%5B%5D=5', class: 'text_link' %>. I'd recommend bookmarking usms.org, as it is one of the best swimming resources on the internet.</p>

    <h3>
      What should I buy?
    </h3>
    <h4>Suit</h4>
    <p>First, you'll need a suit. I prefer Speedo and Tyr brands, although the most important thing is that the suit fits comfortably (snug, but not digging into your skin).</p>
      <ul>
        <li>Ladies: The <%= link_to "Speedo Endurance", 'http://amzn.com/B000YM9MJO', class: 'text_link' %> is the most popular women's suit. This would be a great place to start if you're not sure what suit to buy.</li>
        <li>Men: Drag suits offer good range of motion with a little less 'squeezing'. My current favorite is the <%= link_to "Tyr Mesh Drag Suit", 'http://amzn.com/B000H37OQS', class: 'text_link' %>. The Speedo brand version is just as good.</li>
        <li>Men: The <%= link_to 'Speedo Endurance', 'http://amzn.com/B000YZG7T4', class: 'text_link' %> is great and it comes in brief, square-leg, and jammer (knee-length) cuts.</li>
      </ul>
    <h4>Goggles</h4>
    <p>If you have a swim shop in your area (they're more common than you might think), I recommend visiting to try on several different pairs.</p>
      <ul>
        <li><%= link_to 'Speedo Vanquisher Goggles', 'http://amzn.com/B000F6C6LU', class: 'text_link' %> are my favorite. The Vanquishers come with several different nose pieces that you can switch out to fit your face. I have a clear pair for indoor swimming and a polarized pair for outdoor swimming. If you're just going to get one pair, go with something tinted.</li>
        <li><%= link_to 'Swedish Goggles', 'http://amzn.com/B003VS2RJ0', class: 'text_link' %> are a cheaper option that work well for some people. They come unassembled, so you can customize them to fit you exactly. When you get the fit right, they are suprisingly comfortable.</li>
      </ul>
    <h4>Caps</h4>
      <p>Many swimmers choose not to wear a cap, but for swimmers with longer hair, a cap is quite important.</p>
        <ul>
          <li><%= link_to 'Silicon Caps', 'http://amzn.com/B000F6E2JE', class: 'text_link' %> cost a little more up front but last much longer than the latex caps.</li>
          <li>If you have long hair, a <%= link_to 'Textured Cap', 'http://amzn.com/B001M5TWJW', class: 'text_link'%> is easier to remove without pulling your hair.</li>
        </ul>


    <h3>
    What about open water swimming?
    </h3>
    <p>Watch out for sharks. And try not to get pollution on you. More coming.</p>

  </div>

</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container">
  <%= image_tag("swim_icon_white.png", size: "50") %>
  
  <h1>Welcome to the 100 Mile Swim Challenge!</h1>

  <h2>
    Take the challenge to swim 100 miles in a year.
  </h2>
  
  <div class="progress">
  <% if user_signed_in? %>
    <hr>
    <% @total = Totaler.new().get_total(@user) %>
    <span class="goal_progress">Progress towards goal: <%= @total.round(2) %> / <%= @user.goal %> (<%=(@total*100/@user.goal).round(2) %>%)</span><br />
    <meter min="0" max="<%=@user.goal%>" value="<%= @total %>"></meter><br />
    <%= link_to "New Workout", new_workout_path, class: "btn btn-default" %>
    <%= link_to "All Workouts", workouts_path, class: "btn btn-default" %>
  <% else %>
    <%= link_to "Sign up and swim!", new_user_registration_path, class: "btn btn-default" %>
    <%= link_to "Sign in", user_session_path, class: "btn btn-default" %>
  <% end %>
  </div>

</div>

app/views/static_pages/shallow_end.html.erb
<% provide(:title, 'Shallow End') %>
<div class="container">
  <%= image_tag("swim_icon_white.png", size: "50") %>

  <h1>The Shallow End</h1>

  <h2>
    New swimmers start here
  </h2>

  <div class="text_bg">
  	<h3>
  	Why should I swim?	
  	</h3>
  	<p>Because it's fun and it's good for you!</p>
  	<p>Swimming is easy on your body. Let's face it: for some of us, it's been a while since our last visit to the gym. If it's been a while since you exercised regularly, swimming is a great way to get back in shape. Running can be hard on your knees and ankles, which can discourage beginners. Swimming, on the other hand, is low-impact and carries almost no risk of injury. No matter your current fitness-level, you can get a good cardiovascular workout and build strength by swimming.</p>

  	<h3>
  	How should I swim?
  	</h3>
  	<p>If you just want to get some exercise, it really doesn't matter. If you're in the water and you're moving, you're going to burn calories. However, if you spend some time working on your technique, you'll find that you can swim much further and faster, thereby gaining a lot more benefits from your swim workouts.</p>
  	<p>There are four strokes that are used in competition: backstroke, breaststroke, butterfly, and free-style. Freestyle (sometimes called 'crawl') is the most popular stroke, because it is the fastest and most efficient.</p>
  	<p><%= link_to "Swim Smooth", 'http://www.swimsmooth.com', class: 'text_link'%> looks like a good place for some pointers if you'd like to learn better swimming technique.</p>

  	<h3>
  	Where should I swim?
  	</h3>
  	<p>It's easy to find pools in the summer. For the other nine months of the year, I would suggest finding an indoor pool. Start with your city's parks and recreation website; odds are that your community has an indoor municipal pool. Most universities have an indoor pool and some private gyms have lap pools. Preferrably, the pool you use will be at least 25 yards long.</p>

  	<h3>
  	What do I need?
  	</h3>
  	<p>Not much: a pool, a swimsuit, a pair of goggles, and a towel. Many swimmers also like a swim cap. Check out the <%= link_to "Deep End", deep_end_path, class: 'text_link' %> for more detailed gear recommendations and discussion of kick-boards, pull-buoys, etc.</p>

  	<h3>
  	Do I have to wear a speedo?
  	</h3>
  	<p>No. But you should shouldn't feel nervous about it, either. Most serious swimmers wear speedos, or knee-length (but still tight) 'jammers' when they train. The benefits are reduced resistance in the water and improved range of motion.</p>
  	<p>Just kidding. The speedo is mandatory.</p>

  	<h3>
  	Why 100 miles?
  	</h3>
  	<p>I believe that anyone who is reasonably committed to the goal can swim one hundred miles in a year. You can swim one hundred miles in a year if you go to the pool three times a week and swim ~1200 yards (24 laps). For an experienced swimmer, this distance takes between 15 and 20 minutes. If you're just getting started, it will take you longer to complete this distance, but by the end of the year, you'll be completing that distance in no time.</p>

  </div>

</div>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :units %><br>
    <%= f.radio_button :units, 'yards', :checked => true %>
    <%= label :units_yards, 'Yards' %><br />
    <%= f.radio_button :units, 'meters' %>
    <%= label :units_meters, 'Meters' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<div class="container">

<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout, class:"btn btn-default" %> |
<%= link_to 'Back', workouts_path, class:"btn btn-default" %>

</div>

app/views/workouts/index.html.erb
<div class="container">

<h1 style="margin-bottom:50px;">Listing workouts</h1>

<table id="workouts" cellspacing="10" cellpadding="5"> 
  <thead>
    <tr>
      <th>Distance</th>
      <th>Units</th>
      <th>Miles</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.distance %></td>
        <td><%= workout.units %></td>
        <td><%= workout.distance_as_miles.round(2) %></td>
        <td><%= workout.created_at.strftime("%d %b. %Y") %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path, class: "btn btn-default" %> | 
<%= link_to 'Home', root_path, class: "btn btn-default" %>

</div>

<script>
$(document).ready(function() {
  $('#workouts').dataTable( {
  }).show();

});

</script>

app/views/workouts/new.html.erb
<div class="container">

<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path, class:"btn btn-default" %>

</div>

app/views/workouts/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<span>
  <h1>Distance:</h1>
  <h2><%= @workout.distance %></h2>
</span>

<span>
  <h1>Units:</h1>
  <h2><%= @workout.units %></h2>
</span>

<span>
  <h1>Date:</h1>
  <h2><%= @workout.created_at.strftime("%d %b. %Y") %></h2>
</span>

<%= link_to 'Edit', edit_workout_path(@workout), class: "btn btn-default" %> |
<%= link_to 'Back', workouts_path, class: "btn btn-default" %> | 

<%= link_to 'Home', root_path, class: "btn btn-default" %>

</div>